# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with PNPM pre-installed
FROM node:18-alpine AS builder

# Install pnpm globally
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Copy the package files
COPY typescript/package.json /app/package.json
COPY typescript/pnpm-lock.yaml /app/pnpm-lock.yaml

# Install dependencies using pnpm
RUN pnpm install

# Copy the rest of the TypeScript source code
COPY typescript/tsconfig.json /app/tsconfig.json
COPY typescript/src /app/src

# Build the project using the build script specified
RUN pnpm run build

# Use a lightweight Node.js image for running
FROM node:18-alpine AS release

# Create app directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/dist /app/dist

# Copy package.json and install only production dependencies
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/pnpm-lock.yaml /app/pnpm-lock.yaml
RUN pnpm install --prod

# Set environment variables
ENV NODE_ENV=production
ENV STRIPE_SECRET_KEY=your_stripe_secret_key_here

# Run the server
ENTRYPOINT ["node", "dist/modelcontextprotocol/index.js"]
